spring.datasource.url=jdbc:mysql://localhost:3306/devims?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=myROOT123#@!
spring.jpa.database = MYSQL
spring.jpa.show-sql = true
spring.jpa.hibernate.ddl-auto = create
tokenService.sessionExpiryTime = 15
server.port=8881